delivery_app/backend_apps/backend_auth/urls.py
from django.conf.urls import url

from .views.group import GroupListView, GroupCretaView, GroupUpdateView, GroupDeleteView
from .views.menu import MenuUpdateActiveView, MenuUpdateView, MenuDeleteView
from .views.user import UserCreateView, UserUpdateView, UserDeleteView
from .views.group_permission import GroupPermissionsUpdateView

from .views.user import (UserListView)
from .views.menu import (MenuListView, MenuCreateView)
from .views.permission import (PermissionCreateView, PermissionDeleteView, PermissionListView,
                               PermissionUpdateView)

urlpatterns = [

    # User
    url(r'^user/list/$', UserListView.as_view(), name='user_list'),
    url(r'^user/add/$', UserCreateView.as_view(), name='user_add'),
    url(r'^user/update/(?P<pk>[^/]+)/$', UserUpdateView.as_view(), name='user_update'),
    url(r'^user/delete/(?P<pk>[^/]+)/$', UserDeleteView.as_view(), name='user_delete'),

    url(r'^group/list/$', GroupListView.as_view(), name='group_list'),
    url(r'^group/add/$', GroupCretaView.as_view(), name='group_add'),
    url(r'^group/update/(?P<pk>[^/]+)/$', GroupUpdateView.as_view(), name='group_update'),
    url(r'^group/delete/(?P<pk>[^/]+)/$', GroupDeleteView.as_view(), name='group_delete'),
    url(r'^grouppermissions/update/$', GroupPermissionsUpdateView.as_view(), name='group_permissions_update'),

    # Menu
    url(r'^menu/list/$', MenuListView.as_view(), name='menu_list'),
    url(r'^menu/add/$', MenuCreateView.as_view(), name='menu_add'),
    url(r'^menu/state/(?P<state>[\w\d\-]+)/(?P<pk>[^/]+)/$',
        MenuUpdateActiveView.as_view(), name='menu_state'),
    url(r'^menu/update/(?P<pk>[^/]+)/$', MenuUpdateView.as_view(), name='menu_update'),
    url(r'^menu/delete/(?P<pk>[^/]+)/$', MenuDeleteView.as_view(), name='menu_delete'),

    #
    url(r'^permission/delete/(?P<pk>.*)/$',
        PermissionDeleteView.as_view(), name='permission_delete'),  # x pony
    url(r'^permission/update/(?P<pk>.*)/$',
        PermissionUpdateView.as_view(), name='permission_update'),
    url(r'^permission/add/$',
        PermissionCreateView.as_view(), name='permission_add'),
    url(r'^permission/list/$',
        PermissionListView.as_view(), name='permission_list'),

]

delivery_app/config/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.i18n import JavaScriptCatalog

from backend_apps.access.views import dashboard
from config import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript_catalog'),
    # Backend

    url(r'^backend/', include('backend_apps.backend_auth.urls', namespace='backend')),
    url(r'^access/', include('backend_apps.access.urls', namespace='access')),

    url(r'^$', dashboard, name='dashboard'),
    url(r'^app/', include('apps.myapp.urls', namespace='myapp'))

]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

delivery_app/backend_apps/backend_auth/models.py
from uuid import uuid4

from django.contrib.auth.models import AbstractUser, UserManager, Permission
from django.db import models

# Create your models here.
DNI = 'DNI'
FOREING_CARD = 'FC'
OTHER = 'OTROS'
IDENTITY_TYPE_CHOICES = (
    (DNI, 'DNI'),
    (FOREING_CARD, 'Canet de Extranjería'),
    (OTHER, 'Otros'),
)


class Person(models.Model):
    """Model Person.

        Model for authenticate user and save personal dates.
    """

    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    first_name = models.CharField(u"Firs Name", max_length=50)
    last_name = models.CharField(u"Last Name", max_length=100)
    identity_type = models.CharField(max_length=15, choices=IDENTITY_TYPE_CHOICES, default=DNI)
    identity_num = models.CharField(max_length=20, error_messages={'unique': "eeeee ee"})
    photo = models.ImageField(upload_to='persons', blank=True, null=True)
    email = models.EmailField()
    birth_date = models.DateField(blank=True, null=True)

    updated_at = models.DateTimeField("Updated at", auto_now=True)
    created_at = models.DateTimeField("Created at", auto_now_add=True)

    class Meta:
        verbose_name = u"Person"
        verbose_name_plural = u"Persons"

    def __str__(self):
        return '%s %s %s' % (self.first_name, self.last_name, self.identity_num)


class User(AbstractUser):
    u"""
    Curtom User.
    """
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    person = models.OneToOneField(Person, verbose_name="Person", blank=True, null=True)
    updated_at = models.DateTimeField("Updated at", auto_now=True)
    created_at = models.DateTimeField("Created at", auto_now_add=True)

    objects = UserManager()

    class Meta:
        verbose_name = "User"
        verbose_name_plural = "Users"
        permissions = (
            ('list_user', 'Can list user'),
            ('get_user', 'Can get user'),
        )

    def __str__(self):
        return self.username


class Menu(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    title = models.CharField(u'Título', max_length=50)
    url = models.CharField(max_length=150, default='#')
    pos = models.IntegerField('Position', default=1)
    icon = models.CharField('Icon', max_length=50, null=True, blank=True, default='')
    is_active = models.BooleanField(default=True)
    description = models.TextField(blank=True, null=True)
    permission = models.ForeignKey(Permission, verbose_name="permission", null=True, blank=True)
    parent = models.ForeignKey('self', verbose_name='Parent', null=True, blank=True)

    created_at = models.DateTimeField('Created at', auto_now_add=True)
    updated_at = models.DateTimeField('Updated at', auto_now=True)

    class Meta:
        verbose_name = 'Menu'
        verbose_name_plural = 'Menus'
        permissions = (
            ('list_menu', 'Can list menu'),
            ('get_menu', 'Can get menu'),
        )

    def __str__(self):
        return "%s" % (self.title)

delivery_app/backend_apps/backend_auth/forms/group.py
from crispy_forms.bootstrap import FormActions
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row, Div, Field

from django import forms
from django.contrib.auth.models import Group

from backend_apps.utils.forms import smtSave, btnCancel, btnReset


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        exclude = ('',)

    def __init__(self, *args, **kwargs):
        super(GroupForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_class = 'js-validate form-vertical'
        self.helper.layout = Layout(
            Row(
                Div(
                    Field('name', css_class='input-required'), css_class='col-md-12'
                )
            ),
            Row(
                FormActions(
                    smtSave(),
                    btnCancel(),
                    btnReset(),
                ),
            ),
        )

delivery_app/backend_apps/backend_auth/views/group.py
from django.contrib import messages
from django.contrib.auth.models import Group
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, UpdateView
from django.views.generic.edit import BaseDeleteView
from django.utils.encoding import force_text
from ..forms.group import GroupForm
from backend_apps.utils.decorators import permission_resource_required
from backend_apps.utils.forms import empty
from backend_apps.utils.security import get_dep_objects
from config import settings


class GroupListView(ListView):
    model = Group
    paginate_by = settings.PER_PAGE
    template_name = "auths/group/list.html"

    @method_decorator(permission_resource_required)
    def dispatch(self, request, *args, **kwargs):
        return super(GroupListView, self).dispatch(request, *args, **kwargs)

    def get_paginate_by(self, queryset):
        if 'all' in self.request.GET:
            return None
        return ListView.get_paginate_by(self, queryset)

    def get_queryset(self):
        self.o = empty(self.request, 'o', '-id')
        self.f = empty(self.request, 'f', 'name')
        self.q = empty(self.request, 'q', '')
        column_contains = u'%s__%s' % (self.f, 'contains')
        return self.model.objects.filter(**{column_contains: self.q}).order_by(self.o)

    def get_context_data(self, **kwargs):
        context = super(GroupListView, self).get_context_data(**kwargs)
        context['opts'] = self.model._meta
        context['cmi'] = 'grupo'
        context['title'] = ('Seleccione %s para Cambiar') % ('Grupo')

        context['o'] = self.o
        context['f'] = self.f
        context['q'] = self.q.replace('/', '-')
        return context


class GroupCretaView(CreateView):
    model = Group
    form_class = GroupForm
    template_name = "auths/group/form.html"
    success_url = reverse_lazy("backend:group_list")

    @method_decorator(permission_resource_required)
    def dispatch(self, request, *args, **kwargs):
        return super(GroupCretaView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(GroupCretaView, self).get_context_data(**kwargs)
        context['opts'] = self.model._meta
        context['cmi'] = 'grupo'
        context['title'] = "Agregar Menu"
        return context

    def form_valid(self, form):
        self.object = form.save(commit=True)
        msg = 'El %(name)s "%(obj)s" fue agregado satisfactoriamente' % {
            'name': self.model._meta.verbose_name,
            'obj': self.object
        }

        if self.object.id:
            messages.success(self.request, msg)
        return super(GroupCretaView, self).form_valid(form)


class GroupUpdateView(UpdateView):
    model = Group
    form_class = GroupForm
    template_name = "auths/group/form.html"
    success_url = reverse_lazy("backend:group_list")

    @method_decorator(permission_resource_required)
    def dispatch(self, request, *args, **kwargs):
        pk = self.kwargs.get(self.pk_url_kwarg, None)
        if not pk:
            return HttpResponseRedirect(self.success_url)
        self.kwargs['pk'] = pk
        try:
            self.get_object()
        except Exception as e:
            messages.error(self.request, e)
            return HttpResponseRedirect(self.success_url)
        return super(GroupUpdateView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(GroupUpdateView, self).get_context_data(**kwargs)
        context['opts'] = self.model._meta
        context['cmi'] = 'grupo'
        context['title'] = "Cambiar %s" % "Grupo"
        return context

    def form_valid(self, form):
        self.object = form.save(commit=True)
        msg = 'El %(name)s "%(obj)s" fue cambiado satisfactoriamente' % {
            'name': self.model._meta.verbose_name,
            'obj': self.object
        }
        messages.success(self.request, msg)
        return super(GroupUpdateView, self).form_valid(form)


class GroupDeleteView(BaseDeleteView):
    model = Group
    success_url = reverse_lazy("backend:group_list")

    @method_decorator(permission_resource_required)
    def dispatch(self, request, *args, **kwargs):
        pk = self.kwargs['pk']
        if not pk:
            return HttpResponseRedirect(self.success_url)
        self.kwargs['pk'] = pk
        try:
            self.get_object()
        except Exception as e:
            messages.error(self.request, e)
            return HttpResponseRedirect(self.success_url)
        return super(GroupDeleteView, self).dispatch(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        try:
            d = self.get_object()
            deps, msg = get_dep_objects(d)
            if deps:
                messages.warning(self.request, ('No se puede eliminar %(name)s') % {
                    "name": self.model._meta.verbose_name + ' "' + force_text(d) + '"'
                })
                raise Exception(msg)

            d.delete()
            msg = 'The %(name)s "%(obj)s" was deleted successfully.' % {
                'name': self.model._meta.verbose_name,
                'obj': d
            }
            if not d.id:
                messages.success(self.request, msg)

        except Exception as e:
            messages.error(request, e)

        return HttpResponseRedirect(self.success_url)

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

delivery_app/backend_apps/backend_auth/views/group_permission.py
from django.db import transaction
from django.contrib import messages
from django.contrib.auth.models import Permission, Group
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect
from django.views.generic.list import ListView
from django.utils.decorators import method_decorator

from backend_apps.utils.forms import empty

from backend_apps.utils.decorators import permission_resource_required


class GroupPermissionsUpdateView(ListView):

    """ """
    model = Permission
    # grouppermissions es el controller
    template_name = 'auths/group/group_permission_form.html'
    success_url = reverse_lazy('backend:group_permissions_update')

    @method_decorator(permission_resource_required)
    def dispatch(self, request, *args, **kwargs):
        return super(GroupPermissionsUpdateView, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        self.o = empty(self.request, 'o', '-id')
        self.f = empty(self.request, 'f', 'name')
        self.q = empty(self.request, 'q', '')
        column_contains = u'%s__%s' % (self.f, 'contains')
        return self.model.objects.filter(**{column_contains: self.q}).order_by(self.o)
        # return self.model.objects.all().order_by("content_type__app_label",
        # "content_type__model")

    def get_context_data(self, **kwargs):
        try:
            group_list = Group.objects.all().order_by('-id')
            # obtener los permissions del group para mostrarlos
            privilegios = []
            for g in group_list:
                for p in g.permissions.all():
                    privilegios.append('%s-%s' % (p.id, g.id))
        except Exception as e:
            messages.error(self.request, e)

        context = super(
            GroupPermissionsUpdateView, self).get_context_data(**kwargs)
        context['opts'] = self.model._meta
        context['cmi'] = 'grouppermissions'
        context['title'] = 'Selccione %s para modificar' % ('permissions')

        context['o'] = self.o
        context['f'] = self.f
        context['q'] = self.q.replace('/', '-')

        context['group_list'] = group_list
        context['privilegios'] = privilegios
        return context

    @transaction.atomic
    def post(self, request, *args, **kwargs):
        try:
            sid = transaction.savepoint()
            '''
            group_list = Group.objects.all().order_by('-id')
            old_privilegios_r = []
            for g in group_list:
                for p in g.permissions.all():
                    old_privilegios_r.append('%s-%s' % (p.id, g.id))
            '''
            old_privilegios_r = request.POST.get('old_privilegios')
            if old_privilegios_r:
                old_privilegios_r = old_privilegios_r.split(',')

            # Elimino los antiguos privilegios
            for value in old_privilegios_r:
                # el formato es 1-4 = recurso_id-perfil_id
                data = value.split('-')
                group = Group.objects.get(id=data[1])
                recur = Permission.objects.get(id=data[0])
                group.permissions.remove(recur)

            privilegios_r = request.POST.getlist('privilegios')
            for value in privilegios_r:
                # el formato es 1-4 = recurso_id-perfil_id
                data = value.split('-')
                group = Group.objects.get(id=data[1])
                recur = Permission.objects.get(id=data[0])
                group.permissions.add(recur)
            msg = 'El %(name)s "%(obj)s" fue cambiado satisfactoriamente.' % {
                'name': '',
                'obj': 'permissions'
            }
            messages.success(self.request, msg)
        except Exception as e:
            transaction.savepoint_rollback(sid)
            messages.error(self.request, e)

        return HttpResponseRedirect(self.success_url)

delivery_app/backend_apps/backend_auth/templates/auths/menu/form.html
{% extends "base/base_back.html" %}

{% load i18n crispy_forms_tags %}
{% load l10n %}

{% block breadcrumbs %}
    <a href="{% url 'dashboard' %}">{% trans 'Home' %}</a>
    &rsaquo;
    <a href="{% url 'backend:menu_list' %}">{{ opts.verbose_name_plural|capfirst }}</a>
    &rsaquo; {{ title }}
{% endblock breadcrumbs %}

{% block content_title %}
    {{ opts.verbose_name|capfirst }}|
    <small>{{ title }}</small>
{% endblock content_title %}

{% block content %}

    {% crispy form %}

{% endblock %}

{% block extrajs %}
    {{ block.super }}

    <script type="text/javascript">
        $(function () {
            $("#id_permission").on('change', function () {
                var recurso = $('option:selected', this).text();
                $("#id_url").val(recurso.replace("/\./g", '/'));
                $("#id_url").val(recurso.replace('/*', '/'));

                $("#id_url").val(recurso.replace('_', '/') + "/");
            });
        });
    </script>
{% endblock extrajs %}

delivery_app/backend_apps/backend_auth/templates/auths/menu/list.html
{% extends "base/base_back.html" %}

{% load i18n app_security %}
{% load l10n humanize %}

{% block breadcrumbs %}
    <a href="{% url 'dashboard' %}">{% trans 'Home' %}</a>
    &rsaquo; {{ title }}
{% endblock breadcrumbs %}

{% block content_title %}
    {{ opts.verbose_name_plural|capfirst }}|
    <small>{{ title }}</small>
{% endblock content_title %}

{% block content %}
    <script type="text/javascript">
        $(function () {
            $('table').kgrid({
                form_data: ['{{f}}', '{{q}}'],
                form_to: '{% url "backend:menu_list" %}?f={{f}}&q={{q}}',
                order_attr: 'class=""',
                order_to: '{% url "backend:menu_list" %}?f={{f}}&q={{q}}',
            });
        });
    </script>

    <div class="btn-toolbar btn-toolbar-top">
        <div class="row">
            <div class="btn-actions">
                <a href="{% url 'backend:menu_add' %}" class="btn btn-primary text-bold"
                   title="{% trans 'Add' %} {% trans 'Menu' %}"><i class="fa fa-plus"></i> <span
                        class="hidden-xs"> {% trans 'Add' %}</span></a>
            </div>
        </div>
    </div>
    <div class="container-overflow">
        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
            <tr>
                <th>#</th>

                <th class="col-hidden" data-search="pos"
                    data-order="pos">{% trans 'Position' %}</th>
                <th class="col-hidden" data-search="parent"
                    data-order="parent">{% trans 'Parent' %}</th>
                <th class="col-hidden" data-search="title"
                    data-order="title">{% trans 'title'|capfirst %}</th>
                <th class="col-hidden" data-search="permission"
                    data-order="permission">{% trans 'permission'|capfirst %}</th>
                <th class="col-hidden" data-search="url" data-order="url">{% trans 'URL' %}</th>
                <th class="col-hidden" data-search="icon" data-order="icon">{% trans 'Icon' %}</th>
                <th class="col-hidden" data-search="active"
                    data-order="active">{% trans 'active'|capfirst %}</th>

                <th class="btn-actions col-blocked text-center">{% trans 'Action' %}</th>
            </tr>
            </thead>
            <tbody>
            {% for d in object_list %}
                <tr class="{{ d.is_active|yesno:',danger' }}">
                    <td>{% if is_paginated %}
                        {{ page_obj.start_index|add:forloop.counter0 }}
                    {% else %}
                        {{ forloop.counter }}
                    {% endif %}
                    </td>

                    <td>{{ d.pos }}</td>
                    <td>{{ d.parent.title }}</td>
                    <td>{{ d.title }} </td>
                    <td>
                        {{ d.permission.content_type.app_label }}{{ d.permission_id|yesno:'.,' }}{{ d.permission.codename }}</td>
                    <td>{{ d.url }}</td>
                    <td>{{ d.icon }}</td>
                    <td>
                    <span class="label label-{{ d.is_active|yesno:'primary,success' }}">
                        {% if d.is_active %}{% trans 'Yes'|upper %} {% else %}
                            {% trans 'No'|upper %} {% endif %}
                    </span>
                    </td>


                    <td class="text-center">
                        <div class="btn-group">
                            <a href="{% url 'backend:menu_update' d.pk %}"
                               class="btn btn-info btn-sm text-bold"
                               title="{% trans 'Change' %} {% trans 'Menu' %}" rel="tooltip"><i
                                    class="btn-icon-only fa fa-edit"></i></a>

                            {% if d.is_active %}

                                <a href="{% url 'backend:menu_state' 'ina' d.pk %}"
                                   class="btn btn-success btn-sm text-bold"
                                   title="{% trans 'inactivate'|capfirst %} {% trans 'Menu' %}"
                                   rel="tooltip"><i class="btn-icon-only fa fa-flag"></i>
                                </a>

                                </a>
                            {% else %}

                                <a href="{% url 'backend:menu_state' 'rea' d.pk %}"
                                   class="btn btn-info btn-sm text-bold"
                                   title="{% trans 'reactivate'|capfirst %} {% trans 'Menu' %}"
                                   rel="tooltip"><i class="btn-icon-only fa fa-flag"></i></a>

                            {% endif %}

                            <a href="{% url 'backend:menu_delete' d.pk %}"
                               class="btn btn-danger btn-sm js-confirm text-bold"
                               msg-title="{% trans 'Delete' %} {% trans 'Menu' %}?."
                               msg="{% trans 'Are you sure?' %}<br/>{% trans 'Remember that this operation can not be reversed.' %}"
                               title="{% trans 'Delete' %} {% trans 'Menu' %}" rel="tooltip"><i
                                    class="btn-icon-only fa fa-trash-o"></i></a>
                        </div>

                    </td>
                </tr>
            {% endfor %}
            </tbody>

        </table>
    </div>
    <div class="row">
        {% if is_paginated %}
            {% load paginator %}
            {% paginator %}
        {% else %}
            <div class="col-md-12">
                <ul class="breadcrumbpag">
                    {{ object_list.count }}
                    {% ifequal object_list.count 1 %}{{ opts.verbose_name|capfirst }}{% else %}
                        {{ opts.verbose_name_plural|capfirst }}{% endifequal %}
                </ul>
            </div>
        {% endif %}
    </div>

{% endblock content %}